name: Deploy SimleMessagingApp

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build . -t fajarrmaulanna/simple-messaging-app
      - name: Push docker image to docker hub
        run: docker push fajarrmaulanna/simple-messaging-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull fajarrmaulanna/simple-messaging-app:latest
      - name: Delete old docker container
        run: docker rm -f simple-messaging-app
      - name: Run Docker container with environment variables
        run: |
          docker run -d \
            -e APP_PORT=${{ secrets.APP_PORT }} \
            -e APP_HOST=${{ secrets.APP_HOST }} \
            -e APP_SECRET=${{ secrets.APP_SECRET }} \
            -e APP_NAME="${{ secrets.APP_NAME }}" \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e APP_PORT_SOCKET=${{ secrets.APP_PORT_SOCKET }} \
            -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            -p 8080:8080 -p 4000:4000 \
            --name simple-messaging-app \
            fajarrmaulanna/simple-messaging-app:latest

